version: '3'

services:
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME:
            MONGO_INITDB_ROOT_PASSWORD:
        ports:
            - 27017:27017

    db-admin:
        image: mongo-express
        restart: always
        ports:
            - 8082:8082
        depends_on:
            - db
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME:
            ME_CONFIG_MONGODB_ADMINPASSWORD:
            ME_CONFIG_MONGODB_SERVER: db
            VCAP_APP_PORT: 8082
